version: '3.8'

services:
  db:
    container_name: postgres-db
    image: postgres:17
    ports:
      - "5432:5432"
    env_file:
      - stack.env
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always

  web:
    container_name: web-golang-polisim
    depends_on:
      - db
    ports:
      - "8080:8080"
    env_file:
      - stack.env
    volumes:
      - web_public:/app/public/sim
    image:
      layberize/polisim


volumes:
  pg_data:
  web_public: