version: '3.8'

services:
  db:
    image: memgraph/memgraph:latest
    environment:
      - MEMGRAPH_USER=${DB_USER}
      - MEMGRAPH_PASSWORD=${DB_PASSWORD}
    volumes:
      - mg_lib:/var/lib/memgraph
      - mg_log:/var/log/memgraph
      - mg_etc:/etc/memgraph
    command: ["--log-level=TRACE", "--storage-mode=ON_DISK_TRANSACTIONAL"]
  web:
    depends_on:
      - db
    env_file:
      - stack.env
    image:
      layberize/polisim:vAlpha
    ports:
      - "1350:8080"


volumes:
  mg_lib:
  mg_log:
  mg_etc: