version: '3.8'

services:
  db:
    image: neo4j:5.26.0
    container_name: db-neo4j
    ports:
      - "7687:7687"
    env_file:
      - stack.env
    volumes:
      - neo_data:/data
      - neo_logs:/logs
    restart: always

  web:
    container_name: web-golang-polisim
    depends_on:
      - db
    ports:
      - "1350:8080"
    env_file:
      - stack.env
    volumes:
      - web_data:/app/data
    image:
      layberize/polisim:testing


volumes:
  neo_data:
  neo_logs:
  web_data: