version: '3.8'

services:
  db:
    image: neo4j:5.26.0
    container_name: neo4j
    ports:
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/${DB_PASSWORD}
    volumes:
      - neo_data:/data
      - neo_logs:/logs
    restart: always

  web:
    depends_on:
      - db
    env_file:
      - stack.env
    image:
      layberize/polisim:vAlpha
    ports:
      - "1350:8080"


volumes:
  neo_data:
  neo_logs: