version: '3.8'

services:
  neo-db:
    image: neo4j:5.26.0
    ports:
      - "7687:7687"
    env_file:
      - stack.env
    volumes:
      - neo_data:/data
      - neo_logs:/logs
    restart: always

  postgres-db:
    image: postgres:17
    ports:
      - "5433:5432"
    env_file:
      - stack.env
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always

  web:
    container_name: web-golang-polisim
    depends_on:
      - db
    ports:
      - "8080:8080"
    env_file:
      - stack.env
    volumes:
      - web_public:/app/public
    image:
      layberize/polisim:testing


volumes:
  neo_data:
  neo_logs:
  pg_data:
  web_public: