version: '3.8'

services:
  neo4j:
    image: neo4j:5.26.0
    container_name: neo4j
    ports:
      - "7687:7687"
      - "7474:7474"
    environment:
      - NEO4J_AUTH=none
    volumes:
      - neo_data:/data
      - neo_logs:/logs
    restart: always


volumes:
  neo_data:
  neo_logs: