version: '3.8'

services:
  postgres-db:
    image: postgres:17
    ports:
      - "5432:5432"
    env_file:
      - ../stack.env
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always


volumes:
  pg_data: